export enum WalletMovementLogType {
    CREATE_WALLET = "CREATE_WALLET",
    DISABLE_WALLET = "DISABLE_WALLET",
    ENABLE_WALLET = "ENABLE_WALLET",
    CHARGE_WALLET = "CHARGE_WALLET",
    SELECT_WALLET_AS_DEFAULT = "SELECT_WALLET_AS_DEFAULT",
    PURCHASE_PLAN_WITH_WALLET = "PURCHASE_PLAN_WITH_WALLET",
    PAY_SATURDAY_JOB_WITH_WALLET = "PAY_SATURDAY_JOB_WITH_WALLET",
    REFUND_WALLET = "REFUND_WALLET",
    PAYMENT_REJECTED = "PAYMENT_REJECTED",
}
