import { CustomerId } from "../../../domain/customer/CustomerId";
import { Locale } from "../../../domain/locale/Locale";
import { Order } from "../../../domain/order/Order";
import { OrderId } from "../../../domain/order/OrderId";
import { PaymentOrderId } from "../../../domain/paymentOrder/PaymentOrderId";
import { Plan } from "../../../domain/plan/Plan";
import { PlanVariantId } from "../../../domain/plan/PlanVariant/PlanVariantId";
import { SubscriptionId } from "../../../domain/subscription/SubscriptionId";
import { Week } from "../../../domain/week/Week";
import { WeekId } from "../../../domain/week/WeekId";

export interface IOrderRepository {
    save(order: Order): Promise<void>;
    bulkSave(orders: Order[]): Promise<void>;
    updateMany(orders: Order[]): Promise<void>;
    findAll(locale: Locale): Promise<Order[]>;
    findById(orderId: OrderId, locale: Locale): Promise<Order | undefined>;
    findBy(conditions: any, locale: Locale): Promise<Order[]>;
    findNextTwelveBySubscription(subscriptionId: SubscriptionId): Promise<Order[]>;
    getCountByPaymentOrderIdMap(paymentOrdersIds: PaymentOrderId[]): Promise<{ [key: string]: number }>;
    findByIdList(ordersIds: OrderId[]): Promise<Order[]>;
    findNextTwelveBySubscriptionList(subscriptionsIds: SubscriptionId[]): Promise<Order[]>;
    findByIdOrThrow(orderId: OrderId): Promise<Order>;
    findForBilling(subscriptionsIds: SubscriptionId[], week: Week): Promise<Order[]>;
    findByWeek(weekId: WeekId): Promise<Order[]>;
    findByPaymentOrderId(paymentOrderId: PaymentOrderId): Promise<Order[]>;
    findByPaymentOrderIdList(paymentOrdersIds: PaymentOrderId[]): Promise<Order[]>;
    findActiveOrdersByPaymentOrderId(paymentOrderId: PaymentOrderId): Promise<Order[]>;
    findACtiveOrdersByPaymentOrderIdList(paymentOrdersIds: PaymentOrderId[]): Promise<Order[]>;
    findPastOrdersByCustomerIdList(subscriptionsIds: SubscriptionId[]): Promise<Order[]>;
    findByWeekList(weeksIds: WeekId[]): Promise<Order[]>;
    findByBillingDates(billingDates: Date[]): Promise<Order[]>;
    findByShippingDates(shippingDates: Date[]): Promise<Order[]>;
    findCurrentWeekOrders(): Promise<Order[]>;
    findAllByCustomersIds(customersIds: CustomerId[]): Promise<Order[]>;
    getFirstOrderOfSubscription(subscriptionId: SubscriptionId): Promise<Order | undefined>;
    saveCancelledOrders(orders: Order[]): Promise<void>;
    saveSwappedPlanOrders(orders: Order[], newPlan: Plan, newPlanVariantId: PlanVariantId): Promise<void>;
    saveSkippedAndActiveOrders(skippedOrders: Order[], activeOrders: Order[]): Promise<void>;
    saveOrdersWithNewState(orders: Order[]): Promise<void>;
    addCustomerToOrderOfSubscription(subscriptionId: SubscriptionId, customerId: CustomerId): Promise<void>;
    delete(orderId: OrderId): Promise<void>;
    destroyManyBySubscriptionId(subscriptionId: SubscriptionId): Promise<void>;
}
