export enum Permission {
    CREATE_ADMIN_USER = "CREATE_ADMIN_USER",
    CREATE_PLAN = "CREATE_PLAN",
    UPDATE_PLAN = "UPDATE_PLAN",
    DELETE_PLAN = "DELETE_PLAN",
    VIEW_PLANS = "VIEW_PLANS",
    CREATE_RECIPE = "CREATE_RECIPE",
    UPDATE_RECIPE = "UPDATE_RECIPE",
    DELETE_RECIPE = "DELETE_RECIPE",
    VIEW_RECIPES = "VIEW_RECIPES",
}
